### ISSUE TITLE
Errors << ocs2_pinocchio_interface:cmake

### ISSUE THREAD

**Issue by lbdz** [leggedrobotics/ocs2#58]
I am using ros noetic on ubuntu 20.04. 
After setting up the environment and installing all dependencies, I am running catkin build ocs2 and getting the error:
![Screenshot from 2022-11-22 16-20-09](https://user-images.githubusercontent.com/49032046/203263668-333d50ba-15e4-41ce-a88d-300546a4b24e.png)
I would appreciate any help.

**Comment by Sabinebellmann** [comment]
Hi,
I got the same error. How did you solve it?

**Comment by lbdz** [comment]
> Hi, I got the same error. How did you solve it?

Pinocchio should be placed in the compile directory.

**Comment by Sabinebellmann** [comment]
Thanks. yeah did that then. Did you also use for pinocchio the branch rsl/ocs2_mobile_manipulator_example. With the Master branch i got errors. Unfortunately i still have problems: Now with the hpp-fcl package. I guess you did not get any further errors?

**Comment by JiahengHu** [comment]
> Thanks. yeah did that then. Did you also use for pinocchio the branch rsl/ocs2_mobile_manipulator_example. With the Master branch i got errors. Unfortunately i still have problems: Now with the hpp-fcl package. I guess you did not get any further errors?

What branch for pinocchio and hpp-fcl did you end up using? I'm consistently getting error for the pinocchio package during compilation, something like "error: no matching function for call to ‘hpp::fcl::CollisionObject::CollisionObject(const CollisionGeometryPtr&)’"

Thanks in advance!

**Comment by nuft** [comment]
With the following versions, the package ocs2_mobile_manipulator_ros builds without problems on my Ubuntu 20.04 on ARM64.

```yml
repositories:
  ocs2:
    type: git
    url: https://github.com/leggedrobotics/ocs2.git
    version: ebde452b10d0eceaac45364f7bb8f0ac1038b637
  ocs2_robotic_assets:
    type: git
    url: https://github.com/leggedrobotics/ocs2_robotic_assets.git
    version: b126d00d55f1e67905c3c1516995466df6873c5c
  hpp-fcl:
    type: git
    url: https://github.com/leggedrobotics/hpp-fcl.git
    version: 8be41cba990eaef717bd4d2b4a7bb05c8ae66ccd
  pinocchio:
    type: git
    url: https://github.com/leggedrobotics/pinocchio.git
    version: b86197e04265892c32966736000a01ee4862a060
```

Hope this helps.
